<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
  'Create users' => 'Crear usuarios',
  'Delete any user' => 'Eliminar cualquier usuario',
  'Manage users' => 'Gestionar usuarios',
  'Read any user' => 'Leer cualquier usuario',
  'Update any user' => 'Actualizar cualquier usuario',
  'Update any user\'s attributes' => 'Actualizar atributos de cualquier usuario',
  'Update any user\'s auth item assignments' => 'Actualizar asignaciones de elementos de autenticación de cualquier usuario',
  'Update any user\'s password' => 'Actualizar la contraseña de cualquier usuario ',
  'Update any user\'s status' => 'Actualizar el estado de cualquier usuario',
];
