<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
  'Activate' => 'Activar',
  'Active' => 'Activo',
  'Advanced Search' => 'Búsqueda avanzada',
  'Any' => 'Cualquiera',
  'Authorization roles' => 'Roles de autorización',
  'Create' => 'Crear',
  'Create user' => 'Crear usuario',
  'Created On' => 'Creado el',
  'Deactivate' => 'Desactivar',
  'Disable' => 'Deshabilitar',
  'Disabled' => 'Deshabilitado',
  'Email' => 'Correo electrónico',
  'Email Verified' => 'Correo Electrónico Verificado',
  'Enable' => 'Habilitar',
  'Enabled' => 'Habilitado',
  'Fields with {asterisk} are required.' => 'Los campos con {asterisk} son obligatorios.',
  'Firstname' => 'Nombre',
  'ID' => 'ID',
  'Is Active' => 'Está activo',
  'Is Disabled' => 'Está deshabilitado',
  'Last Visit On' => 'Última visita',
  'Lastname' => 'Apellido',
  'List users' => 'Lista de usuarios',
  'No' => 'No',
  'Not active' => 'Inactivo',
  'Password Set On' => 'Contraseña establecida',
  'Save' => 'Guardar',
  'Search' => 'Buscar',
  'Toggle' => 'Cambiar',
  'Unverified' => 'No verificado',
  'Unverify' => 'anular la verificación',
  'Update user {id}' => 'Actualizar usuario {id}',
  'Updated On' => 'Actualizado',
  'User account has been successfully created or updated.' => 'Cuenta de usuario se ha creado o actualizado correctamente.',
  'Username' => 'Nombre de usuario',
  'Verified' => 'Verificado',
  'Verify' => 'Verificar',
  'Yes' => 'Si',
  'You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.' => 'También puede escribir un operador de comparación (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> o <b>=</b>) al comienzo de cada uno de los valores de búsqueda para especificar cómo se debe hacer la comparación.',
];
