<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
  'Create users' => 'Tworzy użytkowników',
  'Delete any user' => 'Usuwa dowolnego użytkownika',
  'Manage users' => 'Zarządza użytkownikami',
  'Read any user' => 'Odczytuje dowolnego użytkownika',
  'Update any user' => 'Aktualizuje dowolnego użytkownika',
  'Update any user\'s attributes' => 'Aktualizuje dane dowolnego użytkownika',
  'Update any user\'s auth item assignments' => 'Aktualizuje przypisanie elementów uprawnień dowolnego użytkownika',
  'Update any user\'s password' => 'Aktualizuje hasło dowolnego użytkownika',
  'Update any user\'s status' => 'Aktualizuje status dowolnego użytkownika',
];
