<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
  'Active' => 'Aktywny',
  'Advanced Search' => 'Szukanie zaawansowane',
  'Any' => 'Dowolnie',
  'Are you sure you want to delete this user?' => 'Na pewno usunąć tego użytkownika?',
  'Authorization roles' => 'Profile uprawnień',
  'Create' => 'Utwórz',
  'Create user' => 'Utwórz użytkownika',
  'Created On' => 'Utworzony dnia',
  'Delete user {id}' => 'Usuń użytkownika {id}',
  'Disabled' => 'Zablokowany',
  'Enabled' => 'Odblokowany',
  'Email' => 'Email',
  'Email Verified' => 'Email zweryfikowany',
  'Fields with {asterisk} are required.' => 'Pola oznaczone {asterisk} są wymagane.',
  'Firstname' => 'Imię',
  'Is Active' => 'Aktywny',
  'Is Disabled' => 'Wyłączony',
  'Last Visit On' => 'Ostatnia wizyta dnia',
  'Lastname' => 'Nazwisko',
  'List users' => 'Przeglądaj użytkowników',
  'No' => 'Nie',
  'Not active' => 'Nieaktywny',
  'Password Set On' => 'Hasło ustawione dnia',
  'Save' => 'Zapisz',
  'Unverified' => 'Niezweryfikowany',
  'Update' => 'Aktualizuj',
  'Update user {id}' => 'Aktualizuj użytkownika {id}',
  'Updated On' => 'Zaktualizowany dnia',
  'Users manager' => 'Zarządzanie użytkownikami',
  'Username' => 'Nazwa użytkownika',
  'Verified' => 'Zweryfikowany',
  'View user {id}' => 'Szczegóły użytkownika {id}',
  'Yes' => 'Tak',
  'You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.' => 'Możesz poprzedzić każdą szukaną wartość opcjonalnym operatorem porównania (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> lub <b>=</b>).',
  'User account has been successfully created or updated.' => 'Konto użytkownika zostało pomyślnie zapisane.',
];
